### ISSUE TITLE
Bad Management of array with multiple type 

### ISSUE THREAD

**Issue by LasneF** [pb33f/doctor#24]
given this structure 

```
        turnAdjustmentEid:
          type: array
          minItems: 1
          items:
            type:
              - string
              - 'null'
```

the display is not ok 

![image](https://github.com/user-attachments/assets/f9df6c73-ec3d-4b08-b2a2-dde58dde55f4)

in explorer 
![image](https://github.com/user-attachments/assets/2de7fa45-472f-4fea-93e9-06451f08a0e1)

could be array [ string or null ]  , notice that array [ string , null ] could be confusing even if it looks natural  , could conflict with prefixItems notation
