### ISSUE TITLE
Doctor Will Hang Indefinitely on Badly Formatted Self References

### ISSUE THREAD

**Issue by califlower** [pb33f/doctor#5]
As per our discord chat, opened this for tracking on your end since I saw that you prefer issues be on Github.

a `root.yaml`

```yaml
paths:
  /v3/test:
    get:
      summary: test
      operationId: test
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/TestAccountV3"
```

referencing a `schemas.yaml`

```yaml
TestAccountV3:
  type: object
  properties:
    parentAccount:
      $ref: "schemas.yaml#/TestAccountV3"
    liveAccount:
      $ref: "schemas.yaml#/TestAccountV3"
    provisionedForAccount:
      $ref: "schemas.yaml#/TestAccountV3"
``` 

Like so, will hang indefinitely. 

the reason is that 

https://github.com/pb33f/doctor/blob/main/model/high/base/schema_proxy.go#L61 

```go
	for _, ref := range circularRefs {
		if ref.LoopPoint.Definition == sp.Value.GetReference() {
			return true
		}
	}
```
Doesn't match up. `ref.LoopPoint.Definition` is `#/TestAccountV3`, but the `sp.Value.GetReference()` is `schemas.yaml#/TestAccountV3`. This occurs because the `schemas.yaml` has a self reference that uses a file reference (adding in the `schemas.yaml#` to refer to a definition to itself).

As per your recommendation, this is most likely invalid but in that case should error.
